### ISSUE TITLE
Working version?

### ISSUE THREAD

**Issue by GrupoWebex** [padaliyajay/php-autoprefixer#1]
Hey padaliyajay, we are currently working with https://leaverou.github.io/prefixfree/
I see that project, cause we are finding a pure PHP server side solution.
Could you explain what is the current state of the project?
Thanks for share!

**Comment by padaliyajay** [comment]
Hi Grupo

Current is working version. But it is a starter version, so not sure about any bugs.

You can test it. And let me know if any bugs
