### ISSUE TITLE
Where can we specify older browser versions?

### ISSUE THREAD

**Issue by michael-sumner** [padaliyajay/php-autoprefixer#12]
Hello,

Very good thank you for creating this. How can we specify older browser versions?

**Comment by padaliyajay** [comment]
You can edit existing vendor from here
https://github.com/padaliyajay/php-autoprefixer/tree/master/src/Vendor

**Comment by michael-sumner** [comment]
That's great thank you @padaliyajay and have a good day. Will mark this issue as closed now for you.
