### ISSUE TITLE
Support for Older version of Opera

### ISSUE THREAD

**Issue by Linssen21** [padaliyajay/php-autoprefixer#15]
Can you help me in adding support on Older version of Opera

**Comment by padaliyajay** [comment]
Opera is based on webkit. you can define your own CSS rules in this vendor config file
https://github.com/padaliyajay/php-autoprefixer/blob/master/src/Vendor/Webkit.php

**Comment by padaliyajay** [comment]
Now in the new version you can create your own vendor.

```
$autoprefixer->setVendors(array(
    // Omit prefixes for IE
    \Padaliyajay\PHPAutoprefixer\Vendor\Webkit::class,
    \Padaliyajay\PHPAutoprefixer\Vendor\Mozilla::class,
    MyNamespace\Custom\Opera::class // Use custom vendor prefixes
));

$autoprefixer->compile();
```
