### ISSUE TITLE
Scssphp compatibility

### ISSUE THREAD

**Issue by STV11C** [padaliyajay/php-autoprefixer#16]
Hi, I found your project after looking for a PHP autoprefixer that works with scssphp. I just wanted to check with you if this library is still being maintained and if you know if it works with scssphp compiler? 

Thanks

**Comment by padaliyajay** [comment]
You can use this library on raw CSS, so scssphp does not matter, you just
need to use CSS output of scssphp

**Comment by GrupoWebex** [comment]
Not 100% working on MY "fast" test.
I user this light JS library instead: https://projects.verou.me/prefixfree/

**Comment by padaliyajay** [comment]
Yes it is not a good in speed, but speed does not matter when result should be cache in production website. so this is the only one time process after any changes in a source css

**Comment by padaliyajay** [comment]
Yes if speed is priority then this library is not for that case

**Comment by STV11C** [comment]
Thank you both your reply! I will test both out in the coming weeks and let you know how I went.

I am currently using https://scssphp.github.io/scssphp/ to generate CSS (based on user theme settings) on the fly as part of a WordPress theme. It works really well! The core of the theme is Bootstrap 4 (SCSS files), and I have my custom styles which compile a clean CSS file based on the users settings.

However, as SCSSPHP does not have prefix support I am looking at adding a prefixer as an option for the user. I find that Flexbox is the biggest issue on really old iOS and IE versions, so also looking at just manually adding those instead of adding a whole prefix lib.

Thanks gentlemen!

**Comment by Micemade** [comment]
@padaliyajay - any chance for some performance optimization. For my project, it adds 15 + seconds, and the CSS file is really not large ...

**Comment by padaliyajay** [comment]
@Micemade Unfortunately there is no solution for speed issue. I recommend you to save output to separate css file and use it in production.
