### ISSUE TITLE
Compiling newest Bootstrap problems

### ISSUE THREAD

**Issue by kubiqsk** [padaliyajay/php-autoprefixer#17]
While using your autoprefixer with new Bootstrap 5.1.1 correctly compiled by scssphp-1.7.0 I can see that values like these are removed (completely erased from output)

```
background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity)) !important;
color: rgba(var(--bs-body-color-rgb), var(--bs-text-opacity)) !important;
```

**Comment by padaliyajay** [comment]
what is a problem?

**Comment by kubiqsk** [comment]
Sorry I pressed Enter by mistake - my issue is edited now

**Comment by padaliyajay** [comment]
Currently bootstrap 5 not supported

**Comment by kubiqsk** [comment]
Oh and I can see another issue
Expressions like `::-moz-placeholder`, `::-webkit-input-placeholder` or `:-moz-placeholder-shown` can not be used in combination with each other or with unprefixed version - they all need to have separate closure `{}`
Like in here: https://css-tricks.com/almanac/selectors/p/placeholder/

**Comment by kubiqsk** [comment]
yes, well, it's not about Bootstrap, but about CSS prefixing in general
I mentioned Bootstrap just to be more specific and give you a better idea of what I'm talking about
But CSS var() can be used now in every modern browser, also placeholder declarations are pretty common, so this is not issue with Bootstrap, but with CSS compiling in general

**Comment by padaliyajay** [comment]
Yes, There is some issue with CSS function and placeholder. will fix in future when i need. but not right now.

**Comment by Ruud68** [comment]
Hi,
@padaliyajay Thanks for sharing this code! Awesome :)

@kubiqsk I was triggered by this issue and just did a test
Bootstrap 5.1.3 scss > phpscss 1.8.1 > generates
```
.bg-primary {
  --bs-bg-opacity: 1;
  background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity)) !important;
}
```
Then I parse the css file through autoprefixer and the file gets prefixed okay AND I cannot reproduce this issue as the result of the autoprefixed file is:
```
.bg-primary {
  --bs-bg-opacity: 1;
  background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity)) !important;
}
```

**Comment by kubiqsk** [comment]
Hi @Ruud68  and @padaliyajay 
when I compare original compiled bootstrap.css with compiled and prefixed css from Bootstrap 5.1.3 **bootstrap.scss > phpscss 1.9.0 > and this autoprefixer** then I can see these differencies:

1. wrong placeholder prefixes on many places - they can not be in one line, the need separate closure otherwise it will not work:
LEFT generated wrong :: RIGHT original correct
https://img.kubiq.sk/2021-12-14_08-46-02.png

2. completely missing prefixes
`.form-control::-webkit-file-upload-button` on many places https://img.kubiq.sk/2021-12-14_08-48-18.png

3. `:-moz-placeholder-shown` needs separate closure (same issue as placeholders)
https://img.kubiq.sk/2021-12-14_08-50-20.png

4. some `calc()` can be converted to final percentage
https://img.kubiq.sk/2021-12-14_08-54-15.png

5. completely missing color declarations
https://img.kubiq.sk/2021-12-14_08-55-39.png - that's actually the issue I wrote in the beginning of this thread - yes, you're right it's working for `.bg-primary`, but somehow it's not working for `.text-XXX` classes

6. not needed quotes added everywhere
`[role="button"]` can be just `[role=button]`
`[type="button"]` can be just `[type=button]`
`[type="reset"]` can be just `[type=reset]`
`[type="submit"]` can be just `[type=submit]`
and many many more, so file gets bigger, but I'm not sure if this is happening because of phpscss or this autoprefixer... anyway, it can be solved easily with additional `str_replace`

**Comment by Ruud68** [comment]
Hi, maybe an idea to create a reference css file with the issues you see (so not a scss but a css).
With that file we can better troubleshoot this issue here in this repo (wihtout the risk of the issue being in the scss compiler)
is that an idea?

**Comment by kubiqsk** [comment]
Well, I'm comparing official Bootstrap file
https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css
with my generated file
https://scss.kubiq.sk/style.css
and this is unprefixed version
https://scss.kubiq.sk/style-unprefixed.css

I don't use any fancy settings, just compile it
```
require_once 'scssphp-1.9.0/scss.inc.php';
use ScssPhp\ScssPhp\Compiler;
$scss = new Compiler();
$scss->setImportPaths('bootstrap-5.1.3/scss');
$result = $scss->compileString('@import "bootstrap.scss";');
$unprefixed_css = $result->getCss();
file_put_contents( 'style-unprefixed.css', $unprefixed_css );
```

and then prefix it
```
require_once 'vendor/autoload.php';
use Padaliyajay\PHPAutoprefixer\Autoprefixer;
$autoprefixer = new Autoprefixer( $unprefixed_css );
$prefixed_css = $autoprefixer->compile();
file_put_contents( 'style.css', $prefixed_css );
```

**Comment by Ruud68** [comment]
I understand, but there are two things here: the scss compiler (which is a different repo) and the autoprefixer.
e.g. you note 4 (the calc) has nothing to do with autoprefixing (this repo) and things like
```.form-control::-ms-input-placeholder, .form-control::-moz-placeholder, .form-control::-webkit-input-placeholder, .form-control::placeholder {
	color: #6c757d;
	opacity: 1;
}```
is not the same as the compiler / prefixer that BS uses nut is still correct prefixed CSS.

That is why I try to get the scss composer out of the loop and see if the autoprefix css code is correct (which doesn't mean identical to the BS css notation)

**Comment by Ruud68** [comment]
CSS code:
```
.form-control::placeholder {
  color: #6c757d;
  opacity: 1;
}
.form-control::file-selector-button {
  padding: 1rem 1rem;
}
.form-control:focus ~ label, .form-control:not(:placeholder-shown) ~ label, .form-select ~ label {
  opacity: 1;
}
.text-primary {
  --bs-text-opacity: 1;
  --bs-primary-rgb: 13, 110, 253;
  color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;
}
```
Parse with autoprefixer results in:
```
.form-control::-ms-input-placeholder, .form-control::-moz-placeholder, .form-control::-webkit-input-placeholder, .form-control::placeholder {
	color: #6c757d;
	opacity: 1;
}

.form-control::file-selector-button {
	padding: 1rem 1rem;
}

.form-control:focus ~ label, .form-control:not(:placeholder-shown) ~ label, .form-select ~ label {
	opacity: 1;
}

.text-primary {
	--bs-text-opacity: 1;
	--bs-primary-rgb: 13, 110, 253;
	color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;
}
```
This is correct autoprefixed CSS IMO.
What is missing is IE11 support for ::file-selector-button > ::-ms-browse (https://caniuse.com/?search=%3A%3Afile-selector-button)
and
IE 11 support for :placeholder-shown > :-ms-input-placeholder (https://caniuse.com/?search=%3Aplaceholder-shown)

IE11 replacements could be added I think, but question is why would you do that as this browser is not supported anymore?

**Comment by kubiqsk** [comment]
No it's not correct... you can not combine them in one line
Take a look here https://www.w3schools.com/cssref/sel_placeholder.asp
PS: I don't care about IE11

**Comment by Ruud68** [comment]
You are right :)
so this:
```
.form-control::placeholder {
  color: #6c757d;
  opacity: 1;
}
```
should autoprefix to three entries:
```
.form-control::-ms-input-placeholde {
  color: #6c757d;
  opacity: 1;
}
.form-control::-moz-placeholder {
  color: #6c757d;
  opacity: 1;
}
.form-control::placeholder {
  color: #6c757d;
  opacity: 1;
}
```
Do you know if this is a generic rule for placeholders?
@padaliyajay is this even possible with the current code in this repo?

**Comment by kubiqsk** [comment]
Probably anything connected to placeholders pseudos should be separated, like `:-moz-placeholder-shown` too... etc.
I don't know about other special things like this
I didn't investigate source code of this autoprefixer and there is no documentation, so hard to say, but it something that should work without any extra settings

**Comment by Ruud68** [comment]
agree, and I can also only try to 'reverse engineer, so that is why my question was to @padaliyajay 
postcss autoprefixer plugin sets the standard IMO (is used by e.g. Bootstrap). here is their online autoprefixer that could be used for testing etc.: https://autoprefixer.github.io/ just posting here for future reference.

**Comment by kubiqsk** [comment]
Hello,

so let me compare originally compiled bootstrap.css with css compiled with `scssphp-1.9.0` and your version of `php-autoprefixer`

there are missing:
```
::-webkit-file-upload-button {
```

```
.form-control::-webkit-file-upload-button {
```

```
.form-control:hover:not(:disabled):not([readonly])::-webkit-file-upload-button {
```

```
.form-control-sm::-webkit-file-upload-button {
```

```
.form-control-lg::-webkit-file-upload-button {
```

```
.form-floating > .form-control:not(:-moz-placeholder-shown) {
```

```
.form-floating > .form-control:not(:-moz-placeholder-shown) ~ label {
```

```
# in .toast-container {
width: -webkit-max-content;
width: -moz-max-content;
```

```
# in .placeholder-wave {
-webkit-mask-size: 200% 100%;

# in @-webkit-keyframes placeholder-wave {
-webkit-mask-position: -200% 0%;

# in @keyframes placeholder-wave {
-webkit-mask-position: -200% 0%;
```

```
# in .text-primary {
color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;

# in .text-secondary {
color: rgba(var(--bs-secondary-rgb), var(--bs-text-opacity)) !important;

# in .text-success {
color: rgba(var(--bs-success-rgb), var(--bs-text-opacity)) !important;

# in .text-info {
color: rgba(var(--bs-info-rgb), var(--bs-text-opacity)) !important;

# in .text-warning {
color: rgba(var(--bs-warning-rgb), var(--bs-text-opacity)) !important;

# in .text-danger {
color: rgba(var(--bs-danger-rgb), var(--bs-text-opacity)) !important;

# in .text-light {
color: rgba(var(--bs-light-rgb), var(--bs-text-opacity)) !important;

# in .text-dark {
color: rgba(var(--bs-dark-rgb), var(--bs-text-opacity)) !important;

# in .text-black {
color: rgba(var(--bs-black-rgb), var(--bs-text-opacity)) !important;

# in .text-white {
color: rgba(var(--bs-white-rgb), var(--bs-text-opacity)) !important;

# in .text-body {
color: rgba(var(--bs-body-color-rgb), var(--bs-text-opacity)) !important;
```

```
# in .bg-primary {
background-color: rgba(var(--bs-primary-rgb), var(--bs-bg-opacity)) !important;

# in .bg-secondary {
background-color: rgba(var(--bs-secondary-rgb), var(--bs-bg-opacity)) !important;

# in .bg-success {
background-color: rgba(var(--bs-success-rgb), var(--bs-bg-opacity)) !important;

# in .bg-info {
background-color: rgba(var(--bs-info-rgb), var(--bs-bg-opacity)) !important;

# in .bg-warning {
background-color: rgba(var(--bs-warning-rgb), var(--bs-bg-opacity)) !important;

# in .bg-danger {
background-color: rgba(var(--bs-danger-rgb), var(--bs-bg-opacity)) !important;

# in .bg-light {
background-color: rgba(var(--bs-light-rgb), var(--bs-bg-opacity)) !important;

# in .bg-dark {
background-color: rgba(var(--bs-dark-rgb), var(--bs-bg-opacity)) !important;

# in .bg-black {
background-color: rgba(var(--bs-black-rgb), var(--bs-bg-opacity)) !important;

# in .bg-white {
background-color: rgba(var(--bs-white-rgb), var(--bs-bg-opacity)) !important;

# in .bg-body {
background-color: rgba(var(--bs-body-bg-rgb), var(--bs-bg-opacity)) !important;
```

**Comment by kubiqsk** [comment]
@Ruud68 thanks for your effort, but it's still not outputting correct CSS :/

**Comment by Ruud68** [comment]
@kubiqsk correct :) as it will only handle the pseudo codes that are in this repo, the ones in your test aren't and if needed should be added. The test for me was with the current pseudo codes and if my PR creates correct css code for it: I think it does.

But any effort we put in here is useless if there is no reaction from the maintainer: no use in doing effort for a unmaintained repo. That is why I was pinging the maintainer :)

**Comment by kubiqsk** [comment]
@Ruud68 well, we can just take over this project if @padaliyajay will not respond and continue in your repository, or not?
I can also help with code, but this was only small side-project for me... just some idea... so I didn't have time to go through source code and do some adjustments, but now I have another idea how to use it, so probably I will need to make it works

**Comment by padaliyajay** [comment]
Unfortunately i can't work on this right now. i am very busy in another project. you guys can fix this if you want. everyone is welcome

**Comment by padaliyajay** [comment]
'::-webkit-file-upload-button' fixed

**Comment by padaliyajay** [comment]
I will accept PR if anyone want to contribute. but make sure code is well written and working before to commit

**Comment by kubiqsk** [comment]
@padaliyajay your declaration is incorrect, because you put there
`'::file-upload-button' => '::-webkit-file-upload-button'`
but correct one is
`'::file-selector-button' => '::-webkit-file-upload-button'`
but it's working when i change it, so THANKS

another problem is
`:placeholder-shown`
it should be prefixed to
`:-moz-placeholder-shown`
and when I put this rule to
`Mozilla.php`
it works, but there are some non-prefixed rules, like
`.form-floating > .form-control:focus ~ label, .form-floating > .form-control:not(:placeholder-shown) ~ label, .form-floating > .form-select ~ label`
it should be prefixed to
`.form-floating > .form-control:not(:-moz-placeholder-shown) ~ label, .form-floating > .form-select ~ label`
but it's not... :/

**Comment by kubiqsk** [comment]
and still, the biggest problem is, that this autoprefixes is completele deleting some css rules like
`color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;`
will became just empty line

**Comment by Ruud68** [comment]
okay so the pr for the pseudocodes / declarations block is now merged #yeay, will have a look at the deleting of variables next :) and also at the not(:-moz-placeholder-shown).
maybe better to create separate issues for the things you find now as otherwise we are bound to miss things in this lengthy post?

**Comment by padaliyajay** [comment]
Yes right. create new issue for other problems. @kubiqsk @Ruud68

**Comment by kubiqsk** [comment]
:-moz-placeholder-shown - https://github.com/padaliyajay/php-autoprefixer/issues/21
missing colors - https://github.com/padaliyajay/php-autoprefixer/issues/22
