### ISSUE TITLE
Missing Vendor dir?

### ISSUE THREAD

**Issue by jonnybradley** [padaliyajay/php-autoprefixer#2]
Hi
I was trying out your prefixer at last, and added it to my composer.json and as both dev-master and 1.0 versions the Vendor dir is missing... so i get 
`Fatal error: Uncaught Error: Class 'Padaliyajay\PHPAutoprefixer\Vendor\IE' not found...`
Did i miss something?

Will try a manual install in the meantime,

TIA

**Comment by padaliyajay** [comment]
Please make sure the following file is available
php-autoprefixer/src/Vendor/IE.php
