### ISSUE TITLE
Comments removed?

### ISSUE THREAD

**Issue by Ruud68** [padaliyajay/php-autoprefixer#29]
Hi,
noticed that when parsing css with php-autoprefixer, the comments are removed in the resulting css file.
Is there a way to preserve them in the resulting css file?

**Comment by padaliyajay** [comment]
make sure minify option is disabled

**Comment by Ruud68** [comment]
I call it without parameter like documented: `$prefixed_css = $autoprefixer->compile();`

Can you confirm that in your setup the comments are preserved?

**Comment by padaliyajay** [comment]
I have no setup to test

**Comment by Ruud68** [comment]
Well.... you will not believe it, but while debuggin I ended up in Sabberworm package and thought 'Hé, this looks familiar'...
As it turned out I did a PR specifically for Sabberwork dropping the comments on december 28th 2021 (https://github.com/sabberworm/PHP-CSS-Parser/pull/351), this has been merged but the last official release for Sabberworm dates back to 2019.

So when cleaning up my composer packages it reverted my dev-master for sabberwork back to the official release, loosing the comments...

So the 'fix' here is to use the latest dev version of sabberworm instead of the official released one (as that is a very old version.

Sorry for the 'confusion' :)
Closing this one as solved with serious head injury because of banging head against wall :)

**Comment by padaliyajay** [comment]
Comment is not a big thing so i don't want to use dev version otherwise there could be chance of new issue occur. Anyway i hope your wall is ok :)
