### ISSUE TITLE
Missing webkit rule transform-origin

### ISSUE THREAD

**Issue by martijn103** [padaliyajay/php-autoprefixer#4]
I think the rule is missing for transform-origin, It should be prefixed for webkit, no?

'transform-origin' => '-webkit-transform-origin'

**Comment by padaliyajay** [comment]
Hi, Done!

**Comment by padaliyajay** [comment]
You can simply edit and add any vendor rules to vendor files
https://github.com/padaliyajay/php-autoprefixer/tree/master/src/Vendor

**Comment by martijn103** [comment]
Cool, thanks.
