### ISSUE TITLE
Compilation time is to much

### ISSUE THREAD

**Issue by GrupoWebex** [padaliyajay/php-autoprefixer#5]
Hi Jay. 
I was exited about this project, so i have try to implement on my project.
I'm working with compiling and cacheing on the fly, currently working with prefixfree.css

I test it and I advice have a big compile time (10-20+ secs).
Without phpautoprefix (but processing sass, minify, jspack, etc), compile time is 2-3secs.
In other hand, prefixfree.css has a clientside compile time of 50ms...

So, what can you say about it.
I love this feature/package, but on current compile times i have to avoid it.

Thanks for share your work.

**Comment by mongocart** [comment]
Hi, 

Use PHP 7 for speed. Speed not matter because output(css) should be cache.

**Comment by padaliyajay** [comment]
Hi,

Use PHP 7 for speed. Speed not matter because output(CSS) should be cached in the separate CSS file and serve it to visitors
