### ISSUE TITLE
Doesn't properly handle @if statements

### ISSUE THREAD

**Issue by dleffler** [padaliyajay/php-autoprefixer#6]
With css code of:
@if ($menu_align_center = 1) {
  @media (min-width: 769px) {
    #topnavbar.navbar .navbar-nav {
      display: inline-block;
      float: none;
    }
    #topnavbar.navbar .navbar-collapse {
      text-align: center;
    }
  }
}
@media print {
  a[href]:after {
    content: none !important;
  }
}

The output is mangled and looks like:
@if ($menu_align_center = 1) {
    display: inline-block;
    float: none;
} #topnavbar.navbar .navbar-collapse {
      text-align: center;
  }
}

@media print {
    content:none
!important;
}

**Comment by padaliyajay** [comment]
hi dleffler,

You can input scss code in autoprefix. first compile your scss code to css and input css to this autoprefixer

**Comment by dleffler** [comment]
Sorry, this was an scss compiler issue on my end
