### ISSUE TITLE
Comment lines in CSS file was removed

### ISSUE THREAD

**Issue by vuminhluan** [padaliyajay/php-autoprefixer#7]
Sir, I found that my comment lines in CSS file were removed completely after passing to Autoprefixer()
May be because of the PHP CSS Parser.
Could you please help me fix it ?
Sorry my English is bad.

**Comment by padaliyajay** [comment]
I think it is removed by CSS parser. Please make sure you are using the latest version of CSS parser or just download master branch code of CSS parser

**Comment by vuminhluan** [comment]
Problem solved. Just edit function consumeComment() in ParserState.php
Thank you anyway.
