### ISSUE TITLE
Only seems to remove comments?

### ISSUE THREAD

**Issue by andreszs** [padaliyajay/php-autoprefixer#9]
Hi, is there something else I should install with Composer to make this work? I'm using the default installation, and the generated CSS is just the original CSS without comments. No -webkit nor any other prefixes seem to be added at all. Thanks for your support.

**Comment by dleffler** [comment]
You might need to check another scss file...the list of vendor extensions is somewhat limited since most browsers now support the common tag and do not require a vendor specific tag....e.g., ::placeholder is one of those few.

**Comment by dleffler** [comment]
Additionally, it only seems to apply vendor prefixes as found needed [here](http://shouldiprefix.com/#appearance), NOT the overwhelming historical list of vendor prefixes which have now been incorporated into the CSS engine of modern/recent browsers.
